server:
  port: 8081
  servlet:
    context-path: "/crud"

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/movie_web"
    username: root
    password: 250802
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: identity-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

jwt:
  private-key: "tW2gMT6dTuyA0+lKN4Uga/MBT5Nc5BYtgihIfWk+0rVuCRFkZSy7UQkBudkGTPVI/OWSiNA5bxNLAwMKQrco0wbyFn7tgsnzQ/YXY063jM2clETw7rnWA/SaIe8qsQ8fyPMByIh37gtgKEU9tMzXaJ0J9xRfPjIcByZGn5ewcIto9O7ICLtvbM8bU9SZmzm9h21hMqU4JesQ5LrU6HAWAygZjyu53bLBKq8TszQRg0TnjqZLZKebAwyK/vuc+w+KoWw4xwlWyJgBFyhnQjLYZE+sDSa7XL/gKxyc1ixe95occT96G4mtyBGLFnaF9q9JEsiBcJtSFoj9GMLvwm63+HqZO5c5DJNjksXr35xxc+LrD8UqmC1TzTyRq1FGvPfpX10u0B7+GQ+xNNi+EU/8eA=="
  public-key : "FjHkfUpREQIpe4POn4+qCi68lxM2bMTwUbn9GnFwfyBQ83VcR3i6cBg1LLwHyJsZdMcRt2W7RGB0Vw54iDSPO9CJrXHQNc2ukuOSqbFxzntrip/jya1pFElQ9XiO1loDCQKqEm0x1en1XLqRiTeeylrOkCJdcxwyVMsBq1924lCwF6lacTPDT1qM5tUpVdFxpH97bJLYRAHdJ57tnmH0V2Luw9p8qQyCzu07XvPTmQzYZm+bvtCDZhZUVeJuCV/+iE3vbdAzqiRgrM/wVOCWAMhOJIpRA3jumol8LL9QjFfyGXsHwPCylLDxSPaF/3TK3W67Jmy7L6LYGCfTUJYrLuHZKstth7V9drxADBd5hXdf6Gblx3zvwapEXAnoP13a/bb7RS+sAUc7OomLvml67A=="
  access-token: 1
  refresh-token: 24
