server:
  port: 2508

spring:
  application:
    name: api-gateway
  cloud.gateway.routes:
  - id: CRUD
    uri: http://localhost:8080
    predicates:
      - Path=/crud/**
  - id: profile-service
    uri: http://localhost:8083
    predicates:
      - Path=/profile/**
  - id: notification-service
    uri: http://localhost:8085
    predicates:
      - Path=/notification/**
  - id: post-service
    uri: http://localhost:8087
    predicates:
      - Path=${app.prefix-path}/post/**
    filters:
      - StripPrefix=1

app:
  prefix-path: /api
