server:
  port: 2508

spring:
  application:
    name: api-gateway
  cloud.gateway.routes:
  - id: identity-service
    uri: http://localhost:8080
    predicates:
      - Path=${app.prefix-path}/crud/**
    filters:
      - StripPrefix=1
  - id: profile-service
    uri: http://localhost:8083
    predicates:
      - Path=${app.prefix-path}/profile/**
    filters:
      - StripPrefix=1
  - id: notification-service
    uri: http://localhost:8085
    predicates:
      - Path=${app.prefix-path}/notification/**
    filters:
      - StripPrefix=1
  - id: post-service
    uri: http://localhost:8087
    predicates:
      - Path=${app.prefix-path}/post/**
    filters:
      - StripPrefix=1
  - id: post-service
    uri: http://localhost:8089
    predicates:
      - Path=${app.prefix-path}/movie/**
    filters:
      - StripPrefix=1

app:
  prefix-path: /api
