server:
  port: 8087
  servlet:
    context-path: /post

spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/notification-service?authSource=admin