server:
  port: 8089
  servlet:
    context-path: /movie

spring:
  application:
    name: movie-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/notification-service?authSource=admin